machine/book/urls.py
# --*-- coding: utf-8 --*--
__author__ = 'nolan'

from django.conf.urls import url
from machine.book import views, tests

urlpatterns = [
    # 客户管理
    url(r'book_list$', views.book_list, name="book_list"),
    url(r'book_add$', views.book_add, name="book_add"),
    url(r'upload_file$', views.upload_file, name="upload_file"),
]

machine/system/urls.py
# --*-- coding: utf-8 --*--
__author__ = 'nolan'

from django.conf.urls import url
from machine.system import views, tests

urlpatterns = [

    url(r'^$', views.index, name="index"),

    # 用户登录注销
    url(r'login/$', views.login, name="login"),
    url(r'logout/$', views.logout, name="logout"),
    url(r'register/$', views.register, name="register"),

    # 操作日志
    # url(r'^operate_log$', views.operate_log, name="operate_log"),

    # 用户
    url(r'^user_list/(.+)$', views.user_list, name="user_list"),
    url(r'^user_search/$', views.user_search, name="user_search"),
    url(r'^user_role_management/(.+)$', views.user_role_management, name="user_role_management"),
    url(r'^user_profile/(.+)$', views.user_profile, name="user_profile"),
    url(r'^user_edit/(.+)$', views.user_edit, name="user_edit"),
    url(r'^change_password/(.+)$', views.change_password, name="change_password"),
    url(r'^reset_password/(.+)$', views.reset_password, name="reset_password"),
    url(r'^user_add$', views.user_add, name="user_add"),
    url(r'^user_delete', views.user_delete, name="user_delete"),
    url(r'^current_user_profile', views.current_user_profile, name="current_user_profile"),

    # # 添加部门
    # url(r'^dept_add$', views.dept_add, name="dept_add"),

    # 角色
    url(r'^role_list/(.+)$', views.role_list, name="role_list"),
    url(r'^role_permission_management/(.+)$', views.role_permission_management, name="role_permission_management"),
    url(r'^role_edit/(.+)$', views.role_edit, name="role_edit"),
    url(r'^role_add$', views.role_add, name="role_add"),
    url(r'^role_delete$', views.role_delete, name="role_delete"),
    url(r'^user_profile', views.user_profile, name="user_profile"),

    # 权限
    url(r'^permission_list/(.+)$', views.permission_list, name="permission_list"),
    url(r'^permission_edit/(.+)$', views.permission_edit, name="permission_edit"),
    url(r'^permission_add$', views.permission_add, name="permission_add"),
    url(r'^permission_delete$', views.permission_delete, name="permission_delete"),

    # 用户-角色
    url(r'^user_role_list$', views.user_role_list, name="user_role_list"),
    url(r'^user_role_add$', views.user_role_add, name="user_role_add"),
    url(r'^user_role_delete$', views.user_role_delete, name="user_role_delete"),

    # 角色-权限
    url(r'^role_permission_list$', views.role_permission_list, name="role_permission_list"),
    url(r'^role_permission_add$', views.role_permission_add, name="role_permission_add"),
    url(r'^role_permission_delete$', views.role_permission_delete, name="role_permission_delete"),

    # 页面获取session
    url(r'^get_session_permit$', views.get_session_permit, name="get_session_permit"),
    url(r'^get_session_disable$', views.get_session_disable, name="get_session_disable"),

    # 权限认证未通过跳转
    url(r'^auth_fail/$', views.auth_fail, name="auth_fail"),

    url(r'^test$', tests.test_case, name="test_case"),
]

machine/urls.py
# --*-- coding: utf-8 --*--
"""machine URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from machine.book import urls as book_url
from machine.photography import urls as photography_url
from machine.video import urls as video_url
from machine.system import urls as system_url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),

    # 读书
    url(r'^book/', include(book_url)),
    # 摄影
    url(r'^photography/', include(photography_url)),
    # 摄影
    url(r'^video/', include(video_url)),

    # 系统设置
    url(r'^system/', include(system_url)),
    # 首页
    url(r'^$', include(system_url)),
]

machine/video/urls.py
# --*-- coding: utf-8 --*--
__author__ = 'nolan'

from django.conf.urls import url
from machine.video import views

urlpatterns = [
    url(r'^video_list$', views.video_list, name="video_list"),
]

machine/photography/models.py
# --*-- coding: utf-8 --*--
from machine.system.models import User, _
from django.db import models


class Photo(models.Model):
    author = models.ForeignKey(User, verbose_name=_(u"User"), blank=True, null=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    photo_link = models.CharField(max_length=128)
    favor_cnt = models.IntegerField(default=0, null=True)
    dislike_cnt = models.IntegerField(default=0,  null=True)
    upload_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        app_label = "photography"
        db_table = "photo"
        ordering = ("-upload_time", )
        verbose_name = verbose_name_plural = '照片'

    def __unicode__(self):
        return self.name


class Remark(models.Model):
    author = models.ForeignKey(User, verbose_name=_(u"User"), blank=True, null=True)
    content = models.CharField(max_length=256, blank=True, null=True)
    create_time = models.DateTimeField(blank=True, null=True)

    class Meta:
        app_label = "photography"
        db_table = "remark"
        ordering = ("create_time", )
        verbose_name = verbose_name_plural = '照片'

    def __unicode__(self):
        return self.name

machine/system/models.py
# --*-- coding: utf-8 --*--
__author__ = 'nolan'


from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import AbstractUser
from django.db import models


class Department(models.Model):
    class Meta:
        app_label = 'system'
        db_table = "department"
        verbose_name = verbose_name_plural = '部门'
    name = models.CharField(max_length=128)
    parent_id = models.IntegerField(blank=True, null=True)
    manager = models.CharField(max_length=128, blank=True, null=True)
    comment = models.CharField(max_length=128, blank=True, null=True)
    created_time = models.TimeField(blank=True, null=True)
    updated_time = models.TimeField(blank=True, null=True)

    def __unicode__(self):
        return self.name

    @staticmethod
    def create(**kwargs):
        dept = Department(**kwargs)
        dept.save()
        return dept


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'
        verbose_name = verbose_name_plural = '用户'
        app_label = 'system'
        db_table = "user"

    USER_GENDER_CHOICES = (
        ('男', 'male'),
        ('女', 'female'),
        ('保密', 'secrecy'),
    )
    user_id = models.CharField(max_length=128, blank=True, null=True)
    real_name = models.CharField(max_length=128, blank=True, null=True)
    position = models.CharField(max_length=128, blank=True, null=True)
    gender = models.CharField(choices=USER_GENDER_CHOICES, max_length=16, default='SECRECY', blank=True, null=True)
    phone = models.CharField(max_length=64, blank=True, null=True)
    mobile = models.CharField(max_length=64, blank=True, null=True)
    status = models.BooleanField(default=True)
    leader_id = models.CharField(max_length=64, blank=True, null=True)
    dept_id = models.CharField(max_length=64, blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)
    deleted_at = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return self.username

    @staticmethod
    def create_user(**kwargs):
        user = User(**kwargs)
        user.save()
        return user


class Role(models.Model):
    name = models.CharField(max_length=128, unique=True)
    codename = models.CharField(max_length=128, unique=True)

    class Meta:
        app_label = "system"
        db_table = "role"
        ordering = ("name", )
        verbose_name = verbose_name_plural = '角色'

    def __unicode__(self):
        return self.name

    def get_users(self):
        prrs = UserRoleRelation.objects.filter(role=self).exclude(user=None)
        return [prr.user for prr in prrs]


class Permission(models.Model):
    name = models.CharField(_(u"Name"), max_length=100, unique=True)
    codename = models.CharField(_(u"Codename"), max_length=100, unique=True)

    class Meta:
        app_label = "system"
        db_table = "permission"
        verbose_name = verbose_name_plural = '权限'

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.codename)


class UserRoleRelation(models.Model):
    user = models.ForeignKey(User, verbose_name=_(u"User"), blank=True, null=True)
    role = models.ForeignKey(Role, verbose_name=_(u"Role"))

    class Meta:
        app_label = "system"
        db_table = "user_role_relation"
        ordering = ("user", )
        verbose_name = verbose_name_plural = '用户-角色'

    def __unicode__(self):
        return "%s / %s" % (self.user.username, self.role.name)


class RolePermissionRelation(models.Model):
    role = models.ForeignKey(Role, verbose_name=_(u"Role"), blank=True, null=True)
    permission = models.ForeignKey(Permission, verbose_name=_(u"Permission"))

    class Meta:
        app_label = "system"
        db_table = "role_permission_relation"
        ordering = ("role", )
        verbose_name = verbose_name_plural = '角色-权限'

    def __unicode__(self):
        return "%s / %s" % (self.permission.name, self.role)

machine/video/models.py
from django.db import models

# Create your models here.

machine/book/views.py
# -- coding: utf8 --*--

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
import json
import uuid
from machine.system.models import User


def book_list(request):
    return render_to_response('book/book_list.html', locals(), context_instance=RequestContext(request))


def book_add(request):
    print "***********BOOKADD***************"
    return render_to_response('book/book_add.html', locals(), context_instance=RequestContext(request))


def upload_file(request):
     if request.method == 'POST':
        response = {"success": True, "error": "上传成功!"}
        user_name = request.user.username
        user = User.objects.get(username=user_name)
        try:
            DIR = "media/book/"
            file_obj = request.FILES.get('uploadFile', None)
            fileName = str(uuid.uuid4()) + str(file_obj)
            dst_file_path = DIR + fileName
            dst_file = open(dst_file_path, 'wb')
            content = file_obj.read()
            dst_file.write(content)
            dst_file.close()

            return HttpResponse(json.dumps(response), content_type="application/json")

        except Exception, e:
            response["success"] = False
            response["error"] = unicode(e)
            return HttpResponse(json.dumps(response), content_type="application/json")


#
# def _upload(file):
#     '''''图片上传函数'''
#     if file:
#         path=os.path.join(settings.MEDIA_ROOT,'upload')
#         file_name=str(uuid.uuid1())+".jpg"
#         path_file=os.path.join(path,file_name)
#         parser = ImageFile.Parser()
#         for chunk in file.chunks():
#             parser.feed(chunk)
#         img = parser.close()
#         try:
#             if img.mode != "RGB":
#                 img = img.convert("RGB")
#             img.save(path_file, 'jpeg',quality=100)
#         except:
#             return False
#         return True
#     return False
#
#
# def uploadify_script(request):
#     response=HttpResponse()
#     response['Content-Type']="text/javascript"
#     ret="0"
#     file = request.FILES.get("Filedata",None)
#     if file:
#         if _upload(file):
#             ret="1"
#         ret="2"
#     response.write(ret)
#     return response

machine/photography/views.py
# --*-- coding: utf-8 --*--
import datetime
import logging
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from machine.deco import require_login
from machine.photography.models import Photo
from machine.system.models import User

logger = logging.getLogger('django')


def photo_list(request):
    photo_list = Photo.objects.all()
    return render_to_response('photography/photo_list.html', locals(), context_instance=RequestContext(request))


@require_login
def photo_add(request):
    if request.method == "GET":
        return render_to_response('photography/photo_add.html', locals(), context_instance=RequestContext(request))

    else:
        if request.POST.get('photo_link') != '':
            photo_link = request.POST.get('photo_link')
        if request.POST.get('photo_description') != '':
            description = request.POST.get('description')
        if request.session.get('_auth_user_id'):
            session_user_id = request.session.get('_auth_user_id')
            author = User.objects.get(pk=session_user_id)

        upload_time = datetime.datetime.now()
        print photo_link, description

        Photo.objects.create(author=author, photo_link=photo_link, description=description, upload_time=upload_time)
        return HttpResponseRedirect('/')


def photo_vote(request):
    try:
        flag = request.POST.get('flag')
        photo_id = request.POST.get('photo_id')
        photo = Photo.objects.get(pk=photo_id)
        if flag == "vote_favor":
            if not request.session.get('has_favored'):
                print request.session.get('has_favored')
                favor_cnt = photo.favor_cnt + 1
                photo.favor_cnt = favor_cnt
                photo.save()
                request.session['has_favored'] = True
            else:
                print request.session.get('has_favored')
                favor_cnt = photo.favor_cnt - 1
                photo.favor_cnt = favor_cnt
                photo.save()
                request.session['has_favored'] = False
            return HttpResponseRedirect('/')

        elif flag == "vote_dislike":
            if not request.session.get('has_disliked'):
                dislike_cnt = photo.dislike_cnt + 1
                photo.dislike_cnt = dislike_cnt
                photo.save()
                request.session['has_disliked'] = True
            else:
                dislike_cnt = photo.dislike_cnt - 1
                photo.dislike_cnt = dislike_cnt
                photo.save()
                request.session['has_disliked'] = False
            return HttpResponseRedirect('/')

    except Exception as e:
        print e

machine/video/views.py
# --*-- coding: utf-8 --*--
import datetime
import logging
from django.shortcuts import render_to_response
from django.template import RequestContext

logger = logging.getLogger('django')


def video_list(request):
    return render_to_response('video/video_list.html', locals(), context_instance=RequestContext(request))

machine/templates/system/auth_fail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Archiecture</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-table.min.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="/static/img/facio.ico" type="image/x-icon">
    {% include 'link_css.html' %}
    {% include 'head_script.html' %}
    <script type="text/javascript" src="{% static 'js/test.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/JquerySession.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap-table.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.js' %}"></script>
</head>

<body>

{% block innerscript %}
    <script>
        function ajaxclickload(obj_url) {
            htmlobj=$.ajax({url:obj_url,async:false});
            $("#main_content").html(htmlobj.responseText);}

        $(document).ready(function(){
            $(".menu-item").each(function(){
                $(this).click(function(){
                    ajaxclickload($(this).attr("value"));
                });
            });
        });
    </script>
{% endblock %}


<div id="wrapper">
    {% include 'nav.html' %}
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            {% include 'nav_bar_header.html' %}
        </div>
        <div id="main_content" class="main_body">
            <div style="margin-top: 60px; margin-left: 260px;">
                <h4>权限认证未通过， 请联系管理员!</h4>
            </div>
        </div>
    </div>
</div>
</body>
{% include 'foot_script.html' %}
</html>

machine/templates/system/change_password.html
{% extends 'base_ajax.html' %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>添加用户</h5>
                        <div class="ID" value="{{ user_id }}"></div>
                    </div>
                    <div class="ibox-content">
                        <form method="post" id="userForm" class="form-horizontal" action="">
                            {% if error %}
                                <div class="alert alert-warning text-center">{{ error }}</div>
                            {% endif %}
                            {% if msg %}
                                <div class="alert alert-success text-center">{{ msg }}</div>
                            {% endif %}
                            <div class="form-group">
                                <label for="password" class="col-sm-2 control-label">旧密码<span class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="old_password" name="old_password" placeholder="old password" type="text" class="form-control" {% if error %}value="{{ old_password }}" {% endif %}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="password" class="col-sm-2 control-label">密码<span class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="new_password" name="new_password" placeholder="new password" type="text" class="form-control" {% if error %}value="{{ new_password }}" {% endif %}>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button id="cancel_button" class="btn btn-white" type="button">取消</button>
                                    <button id="submit_button" class="btn btn-primary" type="button">保存</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
$('#userForm').validator({
    timely: 2,
    theme: "yellow_right_effect",
    rules: {

    },
    fields: {
        "username": {
            rule: "required",
            tip: "输入用户名",
            ok: "",
            msg: {required: "必须填写!"}
        },
        "password": {
            rule: "required",
            tip: "输入密码",
            ok: "",
            msg: {required: "必须填写!"}
        },

    },
    valid: function(form) {
        form.submit();
    }
});

function ajaxclickload(obj_url) {
    htmlobj=$.ajax({url:obj_url,async:false});
    $("#main_content").html(htmlobj.responseText);
}

$("#submit_button").click(function () {
    var id = $(".ID").attr("value");
    $.ajax({
        cache: true,
        type: "POST",
        url: "/system/change_password/"+id,
        data:$('#userForm').serialize(),
        async: false,
        error: function(resp) {
            alert(resp["msg"]);
        },
        success: function(resp) {
            parent.$.colorbox.close();
            alert(resp["msg"]);
            ajaxclickload("/system/current_user_profile/"+id);

        }
    });
});

$(document).ready(function() {
    $('#cancel_button').click(function(){
        parent.$.colorbox.close();
        return false;
    });
});

</script>


{% endblock %}

machine/templates/system/department_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

machine/templates/system/group_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

machine/templates/system/group_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

machine/templates/system/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Register | Orchid </title>
    <link rel="shortcut icon" href="../static/img/facio.ico" type="image/x-icon">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body class="gray-bg">
    <div class="middle-box text-center loginscreen  animated fadeInDown">
        <div>
            <div>
                <h1 class="logo-name"><img style="width: 100px; width: 100px; border-radius:10px;" src="{% static 'img/logo.png' %}"></h1>
            </div>
            {% if error %}
                <div class="alert alert-danger text-center">{{ error }}</div>
            {% endif %}
            <h2> Orchid </h2>
            <form class="m-t" role="form" method="post" action="/system/register/">
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="用户名" required="length[6~50]">
                </div>
                <div class="form-group">
                    <input type="password" name="password" class="form-control" placeholder="密码" required="">
                </div>
                <div class="form-group">
                    <input type="password" name="password_again" class="form-control" placeholder="再次输入密码" required="">
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">注册</button>
            </form>
            <p class="m-t"> <small><b>Copyright</b> Nolan</small> </p>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="../../static/js/jquery-2.1.1.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>

</body>

</html>

machine/templates/system/role_edit.html
{% extends 'base_ajax.html' %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>编辑角色</h5>
                        <a class="ID" id="{{ role.id }}"></a>

                    </div>
                    <div class="ibox-content">
                        <form method="post" id="roleForm" class="form-horizontal" action="">
                            {% if error %}
                                <div class="alert alert-warning text-center">{{ error }}</div>
                            {% endif %}
                            {% if msg %}
                                <div class="alert alert-success text-center">{{ msg }}</div>
                            {% endif %}
                            <div class="form-group">
                                <label for="rolename" class="col-sm-2 control-label">角色名<span class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="role_name" name="role_name" placeholder="{{ role.name }}" type="text" class="form-control" {% if error %}value="{{ role.name }}" {% endif %}>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="rolename" class="col-sm-2 control-label">代号<span class="red-fonts">*</span></label>
                                <div class="col-sm-8">
                                    <input id="role_codename" name="role_codename" placeholder="{{ role.codename }}" type="text" class="form-control" {% if error %}value="{{ role.codename }}" {% endif %}>
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button id="cancel_button" class="btn btn-white" type="button">取消</button>
                                    <button id="submit_button" class="btn btn-primary" type="button">保存</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
$('#roleForm').validator({
    timely: 2,
    theme: "yellow_right_effect",
    rules: {

    },
    fields: {
        "role_name": {
            rule: "required",
            tip: "输入角色名",
            ok: "",
            msg: {required: "必须填写!"}
        },
    },
    valid: function(form) {
        form.submit();
    }
});


function ajaxclickload(obj_url) {
    htmlobj=$.ajax({url:obj_url,async:false});
    $("#main_content").html(htmlobj.responseText);
}

 $("#submit_button").click(function () {
    var id = $(".ID").attr("id");
    $.ajax({
        cache: true,
        type: "POST",
        url: "/system/role_edit/"+id,
        data:$('#roleForm').serialize(),
        async: false,
        error: function(request) {
            alert("出错！");
        },
        success: function(data) {
            parent.$.colorbox.close();
            ajaxclickload("/system/role_list/1");

        }
    });
});

$(document).ready(function() {
    $('#cancel_button').click(function(){
        parent.$.colorbox.close();
        return false;
    });
});

</script>


{% endblock %}

machine/templates/system/user_role_add.html
{% extends 'base_ajax.html' %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>添加用户-角色</h5>
                    </div>
                    <div class="ibox-content">
                        <form method="post" id="roleForm" class="form-horizontal" action="">
                            {% if error %}
                                <div class="alert alert-warning text-center">{{ error }}</div>
                            {% endif %}
                            {% if msg %}
                                <div class="alert alert-success text-center">{{ msg }}</div>
                            {% endif %}
                            <div class="form-group">
                                <label for="user-form" class="col-sm-2 control-label">用户<span class="red-fonts">*</span></label>
                                <select id="id_user" name="user">
                                    <option value="">---------</option>
                                    {% for user in user_list %}
                                    <option value="{{ user.id }}">{{ user.username }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="role-form" class="col-sm-2 control-label">角色<span class="red-fonts">*</span></label>
                                <select id="id_role" name="role">
                                    <option value="">---------</option>
                                    {% for role in role_list %}
                                    <option value="{{ role.id }}">{{ role.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <button id="cancel_button" class="btn btn-white" type="button">取消</button>
                                    <button id="submit_button" class="btn btn-primary" type="button">保存</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
$('#roleForm').validator({
    timely: 2,
    theme: "yellow_right_effect",
    rules: {

    },
    fields: {
        "user": {
            rule: "required",
            tip: "输入角色名",
            ok: "",
            msg: {required: "必须填写!"}
        },
        "role": {
            rule: "required",
            tip: "输入角色名",
            ok: "",
            msg: {required: "必须填写!"}
        },
    },
    valid: function(form) {
        form.submit();
    }
});

function ajaxclickload(obj_url) {
    htmlobj=$.ajax({url:obj_url,async:false});
    $("#main_content").html(htmlobj.responseText);
}

 $("#submit_button").click(function () {
    $.ajax({
        cache: true,
        type: "POST",
        url: "/system/user_role_add",
        data:$('#roleForm').serialize(),
        async: false,
        error: function(request) {
            alert("Connection error");
        },
        success: function(data) {
            parent.$.colorbox.close();
            ajaxclickload("/system/user_role_list");

        }
    });
});

$(document).ready(function() {
    $('#cancel_button').click(function(){
        parent.$.colorbox.close();
        return false;
    });
});

</script>


{% endblock %}